# Generated by Django 5.2 on 2026-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='user_timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone e.g. Africa/Lagos', max_length=50),
        ),
    ]
