# Generated by Django 5.2 on 2025-10-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_conversation_updated_at_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
