# Generated by Django 5.2 on 2025-12-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_notificationpreference_sentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='morning_briefing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='morning_briefing_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='reminder_lead_time',
            field=models.IntegerField(default=30, help_text='Minutes before event to remind'),
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10),
        ),
    ]
